### PR TITLE
added committee emails (and my insta)

### PR DESCRIPTION
**Pull request by TSeelig**
Added committee email addresses and my Instagram account - totally to check if the insta is working and not at all for personal purposes...

### CODE REVIEW

**Review by luketainton — APPROVED** [review]

**Comment by TSeelig** [comment]
1 sec forgot something

**Comment by luketainton** [comment]
What did you forget?

**Comment by TSeelig** [comment]
See change

**Comment by TSeelig** [comment]
ugh forgot one more thing

**Comment by luketainton** [comment]
Yeah sure whatever

**Comment by TSeelig** [comment]
Okay I think that's everything

**Pull request merged**
