### PR TITLE
Added image and contributing section

### PR DESCRIPTION
**Pull request by PandelisZ**
This commit is based on some of the things learnt in the campus-experts technical writing workshop. An image has been added to make the readme more visual, the description provides context for the repo and there has been a contributing guideline added. Build and test instructions we're simple and straightforward enough i believe so they remained the same

### CODE REVIEW

**Comment by luketainton** [comment]
This a lot better than the original readme. Good job.

**Comment by PandelisZ** [comment]
Approve it and I shall merge! I'd like to do keep this rule for all additions and enhancements,

Infact i've just enabled this
screen shot 2017-04-27 at 22 07 37

**Review by luketainton — APPROVED** [review]

**Comment by luketainton** [comment]
Wouldn't do it on my phone apparently :/

**Comment by luketainton** [comment]
Protecting master is an excellent idea 👍

**Pull request merged**
