### PR TITLE
Updated navbar to always float at top

### LINKED ISSUE #112: Epic:1 Story:1 Change navbar to always float at the top
## Description
At current navbar goes down on the screen when 'home' is selected or when index.html is first loaded as can be seen below.

Site Index showing navbar position

This is in general poor accessibility design and a nuisance when navigating.

## To Do
Redesign to have navbar always float at top of page at all times.

## Checklist

- [x] Navbar always floats at top of page.

### PR DESCRIPTION
**Pull request by TSeelig**
decoupled two JS files and replicated some lost functionality.
Adapted navbar to appear ontop of all other objects as it was appearing behind images.

Fixes #112

### CODE REVIEW

**Comment by luketainton** [comment]
Awaiting Docker build results

**Comment by TSeelig** [comment]
Docker build successful.

**Comment by luketainton** [comment]
Due to the HTTPS check, I need to make file modifications on my local copy in order to view the site.

**Review by luketainton — CHANGES_REQUESTED** [review]
@CoffeeOwl97 the site doesn't scroll to sections anymore - it jumps around. Can you put back those two external jQuery libraries please?

**Comment by TSeelig** [comment]
@luketainton please update review on latest code.

**Comment by luketainton** [comment]
Two minutes...

**Review by luketainton — APPROVED** [review]

**Comment by luketainton** [comment]
@CoffeeOwl97 That's better! One last thing - could you make the navbar an actual rectangle? The bottom corners curve around right now, and it'll look better if it's a rectangle.

**Comment by luketainton** [comment]
@CoffeeOwl97 I've done it I think - can you take a look?

**Comment by TSeelig** [comment]
One sec

**Comment by TSeelig** [comment]
Changes are good.

**Comment by luketainton** [comment]
Ready to merge? @CoffeeOwl97

**Pull request merged**
