### PR TITLE
Set up new branch ready for new committee roles

### PR DESCRIPTION
**Pull request by luketainton**

### CODE REVIEW

**Comment by luketainton** [comment]
@PandelisZ Not sure if this is needed, but I thought it might make our lives easier in a week's time?

**Comment by PandelisZ** [comment]
`>.>`
Lives easier psh, this whole thing needs a refactor

Looks fine yeah, Not going to approve obviously since we need new committee to be put in

**Comment by PandelisZ** [comment]
Also i think in general, things like this should probably remain as an issue in regards to the traditional GitHub flow until ready since a pull request should mean that the code is production ready

**Comment by luketainton** [comment]
OK, I’ll sort that out in a minute. Cheers for the advice.

**Comment by luketainton** [comment]
Not merging, this will be done once the new committee is announced.

**Pull request closed without merging**
