### PR TITLE
Jekyll #14

### PR DESCRIPTION
**Pull request by PandelisZ**
In accordance with #14 
ive done the things

- [x] Index => Jekyll  (index.yml)
- [x] commitee => commitee.yml
- [x] events => events.yml

Now all the data is easily changable in the _data directory.

All you need to do is just append new events to the top of the events file and new events will appear! 

Code and chill is a permanent fixture

### CODE REVIEW

**Comment by PandelisZ** [comment]
This is why i closed your pull tom sorry

**Comment by PandelisZ** [comment]
TRAVIS why u broken! 😠

**Comment by luketainton** [comment]
Why don't you ask Amazon?

**Comment by PandelisZ** [comment]
https://www.traviscistatus.com/incidents/hmwq9yy5dh9d It is amazons fault actually

**Review by luketainton — CHANGES_REQUESTED** [review]
The images of the team don't load as Jekyll is case sensitive - just capitalise them and it'll be fine!

**Review by luketainton — COMMENTED** [review]
The images should load now.

**Comment by luketainton** [comment]
Is there any way be could add a gap between rows of events? At the moment if 4 events are added and it goes into a second row they are so close they might as well be glued together.

**Review by luketainton — APPROVED** [review]

**Comment by PandelisZ** [comment]
i limited it to 2 events so 3 in total though :/

**Comment by PandelisZ** [comment]
9ab5491 added test data that i corrected, don't leave test data in a pull request destined for prod plz 😢 You can make further pull requests to branches other than master like this one also in cases like that.

**Comment by PandelisZ** [comment]
Travis is down, I've decided that the test has passed. So it must be true.

**Pull request merged**
