### PR TITLE
Update Nokogiri version

### PR DESCRIPTION
**Pull request by luketainton**

### CODE REVIEW

**Comment by luketainton** [comment]
@PandelisZ The Travis build has stopped :( What have I done?

**Comment by TSeelig** [comment]
Latest build passed travis

**Comment by luketainton** [comment]
What? Not fair :(

**Comment by TSeelig** [comment]
See image attached, or just check latest travis build.

screen shot 2018-07-17 at 17 09 28

**Comment by TSeelig** [comment]
Welcome to the world of code :)

**Review by TSeelig — APPROVED** [review]
Travis build now passes, ready to merge?

**Comment by luketainton** [comment]
Sure thing

**Comment by luketainton** [comment]
Now we wait to see if the site builds....

**Comment by TSeelig** [comment]
yep..

**Comment by TSeelig** [comment]
She's working like a gem (pun maybe intended).

**Comment by luketainton** [comment]
No. Bad @CoffeeOwl97.

**Pull request merged**
