### PR TITLE
Security

### PR DESCRIPTION
**Pull request by TSeelig**
PLZ WORK

### CODE REVIEW

**Comment by PandelisZ** [comment]
Lul this is only ever used in CI I don't think it's much of a security concern if this doesnt work

**Review by luketainton — APPROVED** [review]

**Comment by TSeelig** [comment]
Shall we just remove nokogiri completely? Or is it a dependency of something we actually use?

**Comment by luketainton** [comment]
Need it for Jekyll

**Comment by luketainton** [comment]
Give me a min, gonna look at Travis' logs.

**Comment by TSeelig** [comment]
build failed, merge anyway?

**Comment by luketainton** [comment]
No

**Comment by luketainton** [comment]
Only problem now is no favicon on events/index.html. @CoffeeOwl97 could you add?

**Comment by TSeelig** [comment]
Yeh, I can add a favicon.

**Comment by luketainton** [comment]
Did you commit it yet?

**Comment by TSeelig** [comment]
Omw home from uni so ill do it when im back home

**Comment by luketainton** [comment]
Yay!

**Pull request merged**
