### PR TITLE
Update CODEOWNERS

### PR DESCRIPTION
**Pull request by luketainton**

### CODE REVIEW

**Review by PandelisZ — DISMISSED** [review]
<3 that's sweet thanks

**Review by TSeelig — DISMISSED** [review]
Remove Alex, He did not ask for this and will probably just be annoyed by it.

**Review by TSeelig — APPROVED** [review]

**Comment by PandelisZ** [comment]
does codeowners not go in .github/codeowners?

**Comment by luketainton** [comment]
It doesn’t matter.

**Pull request merged**
